// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stevia/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetSweetnerRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSweetnerRequest) Reset()         { *m = QueryGetSweetnerRequest{} }
func (m *QueryGetSweetnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSweetnerRequest) ProtoMessage()    {}
func (*QueryGetSweetnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8598d22f14214ab0, []int{0}
}
func (m *QueryGetSweetnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSweetnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSweetnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSweetnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSweetnerRequest.Merge(m, src)
}
func (m *QueryGetSweetnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSweetnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSweetnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSweetnerRequest proto.InternalMessageInfo

func (m *QueryGetSweetnerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetSweetnerResponse struct {
	Sweetner *Sweetner `protobuf:"bytes,1,opt,name=Sweetner,proto3" json:"Sweetner,omitempty"`
}

func (m *QueryGetSweetnerResponse) Reset()         { *m = QueryGetSweetnerResponse{} }
func (m *QueryGetSweetnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSweetnerResponse) ProtoMessage()    {}
func (*QueryGetSweetnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8598d22f14214ab0, []int{1}
}
func (m *QueryGetSweetnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSweetnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSweetnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSweetnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSweetnerResponse.Merge(m, src)
}
func (m *QueryGetSweetnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSweetnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSweetnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSweetnerResponse proto.InternalMessageInfo

func (m *QueryGetSweetnerResponse) GetSweetner() *Sweetner {
	if m != nil {
		return m.Sweetner
	}
	return nil
}

type QueryAllSweetnerRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSweetnerRequest) Reset()         { *m = QueryAllSweetnerRequest{} }
func (m *QueryAllSweetnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSweetnerRequest) ProtoMessage()    {}
func (*QueryAllSweetnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8598d22f14214ab0, []int{2}
}
func (m *QueryAllSweetnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSweetnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSweetnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSweetnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSweetnerRequest.Merge(m, src)
}
func (m *QueryAllSweetnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSweetnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSweetnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSweetnerRequest proto.InternalMessageInfo

func (m *QueryAllSweetnerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSweetnerResponse struct {
	Sweetner   []*Sweetner         `protobuf:"bytes,1,rep,name=Sweetner,proto3" json:"Sweetner,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSweetnerResponse) Reset()         { *m = QueryAllSweetnerResponse{} }
func (m *QueryAllSweetnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSweetnerResponse) ProtoMessage()    {}
func (*QueryAllSweetnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8598d22f14214ab0, []int{3}
}
func (m *QueryAllSweetnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSweetnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSweetnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSweetnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSweetnerResponse.Merge(m, src)
}
func (m *QueryAllSweetnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSweetnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSweetnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSweetnerResponse proto.InternalMessageInfo

func (m *QueryAllSweetnerResponse) GetSweetner() []*Sweetner {
	if m != nil {
		return m.Sweetner
	}
	return nil
}

func (m *QueryAllSweetnerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetSweetnerRequest)(nil), "evanforbes.stevia.stevia.QueryGetSweetnerRequest")
	proto.RegisterType((*QueryGetSweetnerResponse)(nil), "evanforbes.stevia.stevia.QueryGetSweetnerResponse")
	proto.RegisterType((*QueryAllSweetnerRequest)(nil), "evanforbes.stevia.stevia.QueryAllSweetnerRequest")
	proto.RegisterType((*QueryAllSweetnerResponse)(nil), "evanforbes.stevia.stevia.QueryAllSweetnerResponse")
}

func init() { proto.RegisterFile("stevia/query.proto", fileDescriptor_8598d22f14214ab0) }

var fileDescriptor_8598d22f14214ab0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xda, 0x30,
	0x18, 0x87, 0x71, 0xa6, 0x4d, 0x9b, 0x91, 0x76, 0xb0, 0x34, 0x0d, 0xa1, 0x29, 0x9a, 0x32, 0x6d,
	0x63, 0x6c, 0xb3, 0x07, 0xbb, 0x4f, 0x62, 0x07, 0xb8, 0x6e, 0xf4, 0xc6, 0xcd, 0x81, 0xb7, 0xa9,
	0xa5, 0x10, 0x87, 0xd8, 0xd0, 0xa2, 0xaa, 0x97, 0x7e, 0x82, 0x4a, 0xfd, 0x04, 0x15, 0x5f, 0xa6,
	0x47, 0xaa, 0x5e, 0x7a, 0xac, 0xa0, 0x1f, 0xa4, 0x22, 0x76, 0xf8, 0x53, 0x40, 0x94, 0x53, 0x22,
	0xdb, 0xcf, 0xfb, 0x3e, 0xbf, 0xbc, 0x0e, 0x26, 0x4a, 0xc3, 0x40, 0x70, 0xd6, 0xeb, 0x43, 0x32,
	0xa4, 0x71, 0x22, 0xb5, 0x24, 0x05, 0x18, 0xf0, 0xe8, 0x50, 0x26, 0x3e, 0x28, 0x6a, 0xb6, 0xed,
	0xa3, 0xf8, 0x21, 0x90, 0x32, 0x08, 0x81, 0xf1, 0x58, 0x30, 0x1e, 0x45, 0x52, 0x73, 0x2d, 0x64,
	0xa4, 0x0c, 0x57, 0x2c, 0xb7, 0xa5, 0xea, 0x4a, 0xc5, 0x7c, 0xae, 0xc0, 0x14, 0x64, 0x83, 0x8a,
	0x0f, 0x9a, 0x57, 0x58, 0xcc, 0x03, 0x11, 0xa5, 0x87, 0xed, 0xd9, 0x77, 0xb6, 0xaf, 0x3a, 0x06,
	0xd0, 0x11, 0x24, 0x66, 0xd9, 0xfb, 0x86, 0xdf, 0xff, 0x9f, 0x81, 0x0d, 0xd0, 0x07, 0x76, 0xa7,
	0x09, 0xbd, 0x3e, 0x28, 0x4d, 0xde, 0x62, 0x47, 0x74, 0x0a, 0xe8, 0x23, 0x2a, 0xbd, 0x69, 0x3a,
	0xa2, 0xe3, 0xb5, 0x70, 0x61, 0xfd, 0xa8, 0x8a, 0x65, 0xa4, 0x80, 0xfc, 0xc1, 0xaf, 0xb3, 0xb5,
	0x94, 0xc8, 0x57, 0x3d, 0xba, 0x2d, 0x14, 0x9d, 0xd3, 0x73, 0xc6, 0xe3, 0x56, 0xa3, 0x16, 0x86,
	0x4f, 0x35, 0xea, 0x18, 0x2f, 0xc2, 0xd8, 0xe2, 0x5f, 0xa8, 0x49, 0x4e, 0x67, 0xc9, 0xa9, 0xf9,
	0x94, 0x36, 0x39, 0xfd, 0xc7, 0x03, 0xb0, 0x6c, 0x73, 0x89, 0xf4, 0x46, 0xc8, 0xfa, 0xaf, 0xf4,
	0xd8, 0xe8, 0xff, 0x62, 0x5f, 0x7f, 0xd2, 0x58, 0x91, 0x74, 0x52, 0xc9, 0xaf, 0x3b, 0x25, 0x4d,
	0xf3, 0x65, 0xcb, 0xea, 0x8d, 0x83, 0x5f, 0xa6, 0x96, 0x64, 0x84, 0x16, 0x4e, 0xa4, 0xb2, 0xdd,
	0x66, 0xcb, 0xf8, 0x8a, 0xd5, 0x7d, 0x10, 0x63, 0xe2, 0xfd, 0x3a, 0xbf, 0x7d, 0xb8, 0x74, 0xca,
	0xa4, 0xc4, 0x66, 0xec, 0x4f, 0x03, 0xb3, 0xec, 0xe6, 0xac, 0x5e, 0x20, 0x76, 0x2a, 0x3a, 0x67,
	0xe4, 0x0a, 0xe1, 0x7c, 0x56, 0xa6, 0x16, 0x86, 0x3b, 0x45, 0xd7, 0x07, 0xbc, 0x53, 0x74, 0xc3,
	0xbc, 0xbc, 0xef, 0xa9, 0xe8, 0x67, 0xf2, 0xe9, 0x19, 0xa2, 0x7f, 0xeb, 0xd7, 0x13, 0x17, 0x8d,
	0x27, 0x2e, 0xba, 0x9f, 0xb8, 0xe8, 0x62, 0xea, 0xe6, 0xc6, 0x53, 0x37, 0x77, 0x37, 0x75, 0x73,
	0xad, 0x1f, 0x81, 0xd0, 0x47, 0x7d, 0x9f, 0xb6, 0x65, 0x77, 0x53, 0xa1, 0x93, 0xec, 0x45, 0x0f,
	0x63, 0x50, 0xfe, 0xab, 0xf4, 0x97, 0xf9, 0xfd, 0x18, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x10, 0x40,
	0x79, 0xc3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Sweetner(ctx context.Context, in *QueryGetSweetnerRequest, opts ...grpc.CallOption) (*QueryGetSweetnerResponse, error)
	SweetnerAll(ctx context.Context, in *QueryAllSweetnerRequest, opts ...grpc.CallOption) (*QueryAllSweetnerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Sweetner(ctx context.Context, in *QueryGetSweetnerRequest, opts ...grpc.CallOption) (*QueryGetSweetnerResponse, error) {
	out := new(QueryGetSweetnerResponse)
	err := c.cc.Invoke(ctx, "/evanforbes.stevia.stevia.Query/Sweetner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SweetnerAll(ctx context.Context, in *QueryAllSweetnerRequest, opts ...grpc.CallOption) (*QueryAllSweetnerResponse, error) {
	out := new(QueryAllSweetnerResponse)
	err := c.cc.Invoke(ctx, "/evanforbes.stevia.stevia.Query/SweetnerAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Sweetner(context.Context, *QueryGetSweetnerRequest) (*QueryGetSweetnerResponse, error)
	SweetnerAll(context.Context, *QueryAllSweetnerRequest) (*QueryAllSweetnerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Sweetner(ctx context.Context, req *QueryGetSweetnerRequest) (*QueryGetSweetnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sweetner not implemented")
}
func (*UnimplementedQueryServer) SweetnerAll(ctx context.Context, req *QueryAllSweetnerRequest) (*QueryAllSweetnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SweetnerAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Sweetner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSweetnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sweetner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evanforbes.stevia.stevia.Query/Sweetner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sweetner(ctx, req.(*QueryGetSweetnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SweetnerAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSweetnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SweetnerAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evanforbes.stevia.stevia.Query/SweetnerAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SweetnerAll(ctx, req.(*QueryAllSweetnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evanforbes.stevia.stevia.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sweetner",
			Handler:    _Query_Sweetner_Handler,
		},
		{
			MethodName: "SweetnerAll",
			Handler:    _Query_SweetnerAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stevia/query.proto",
}

func (m *QueryGetSweetnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSweetnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSweetnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSweetnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSweetnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSweetnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sweetner != nil {
		{
			size, err := m.Sweetner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSweetnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSweetnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSweetnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSweetnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSweetnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSweetnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sweetner) > 0 {
		for iNdEx := len(m.Sweetner) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sweetner[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetSweetnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSweetnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sweetner != nil {
		l = m.Sweetner.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSweetnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSweetnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sweetner) > 0 {
		for _, e := range m.Sweetner {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetSweetnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSweetnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSweetnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSweetnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSweetnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSweetnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sweetner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sweetner == nil {
				m.Sweetner = &Sweetner{}
			}
			if err := m.Sweetner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSweetnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSweetnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSweetnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSweetnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSweetnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSweetnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sweetner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sweetner = append(m.Sweetner, &Sweetner{})
			if err := m.Sweetner[len(m.Sweetner)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
